name: Deploy to EKS

on: workflow_dispatch

env:
  EKS_CLUSTER_NAME: sysdig-voting-app
  AWS_REGION: us-east-2

jobs:
  
  build:
    
    name: Deployment
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials 
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_DEV_GITHUB_ACTION_ROLE }}
        aws-region: ${{env.AWS_REGION}}

      
    - name: Update kube config
      run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

    - name: Deploy to EKS

      run: |
        kubectl apply -f k8s-specifications/db-deployment.yaml --validate=false

